swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: User Transactions API
      description: API to dispay the transactions' list for the current month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction" 
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
          
  /user/profile/transaction/{id}:
    post:
      security:
        - Bearer: []
      tags:
        - Single transaction
      summary: User Single Transaction API
      description: API to edit a new transaction
      parameters:
        type:
        - in: path
          name: id
          description: ID of transaction to fetch
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Create a transaction
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        '200':
          description: User transaction created successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Single transaction
      summary: User Single Transaction API
      description: API to update a user transaction
      parameters:
        - in: path
          name: id
          description: ID of transaction to fetch
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update selected transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionInfos"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction modified successfully
          schema:
            $ref: "#/definitions/TransactionInfos"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
    get:
      security:
        - Bearer: []
      tags:
        - Single transaction
      summary: User Single Transaction API
      description: API to retrieve a user transaction
      parameters:
        - in: path
          name: id
          description: ID of transaction to fetch
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successfully
          schema:
            $ref: "#/definitions/TransactionInfos"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Single transaction
      summary: User Single Transaction API
      description: API to delete a user transaction
      parameters:
        - in: path
          name: id
          description: ID of transaction to fetch
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "204":
          description: User transaction deleted successfully
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  
  Transaction:
      type: object
      properties:
        id:
          type: string
          description: transaction's ID
          example: dbdvs561dbdb
        date:
          type: string
          format: date-time
          description: transaction's date
          example: '2022-03-22'
        description:
          type: string
          description: transaction's description
          example: Restole16
        amount:
          type: integer
          format: number
          description: transaction's amount
          example: 40
        balance:
          type: integer
          format: number
          description: account balance after transaction
          example: 3210  
        infos:
          type: object
          $ref: "#/definitions/TransactionInfos"
          
  TransactionInfos: 
      type: object
      properties: 
        transaction type:
          type: string
          description: transaction's type
          example: Electronic
        category:
          type: string
          description: transaction's category
          example: Food
        notes:
          type: string
          description: transaction's notes
          example: sushi  
          