swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  # /user/profile/transactions:
  # get:
  #   tags:
  #     - User Transaction
  #   summary: Account's transactions of the month
    # TO DO : 
    # method : GET
    # response : array of object 
    # for each object : 
    # date = string
    # description = string 
    # amount = float 
    # balance = float 
    # type = string
    # category = string 
    # note =  string      


securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  
  Transactions:
    type : array
    properties: 
      id:
        type: string
        description: transaction's ID
        example: dbdvs561dbdb
      date:
        type: string
        format: date-time
        description: transaction's date
        example: '2022-03-22'
      description:
        type: string
        description: transaction's description
        example: Restole16
      amount:
        type: integer
        format: number
        description: transaction's amount
        example: 40
      balance:
        type: integer
        format: number
        description: account balance after transaction
        example: 3210  
      transaction type:
        type: string
        description: transaction's type
        example: Electronic
      category:
        type: string
        description: transaction's category
        example: Food
      notes:
        type: string
        description: transaction's notes
        example: sushi    
    Transaction:
      type: object
      properties:
        id:
          type: string
          description: transaction's ID
          example: dbdvs561dbdb
        date:
          type: string
          format: date-time
          description: transaction's date
          example: '2022-03-22'
        description:
          type: string
          description: transaction's description
          example: Restole16
        amount:
          type: integer
          format: number
          description: transaction's amount
          example: 40
        balance:
          type: integer
          format: number
          description: account balance after transaction
          example: 3210  
        transaction type:
          type: string
          description: transaction's type
          example: Electronic
        category:
          type: string
          description: transaction's category
          example: Food
        notes:
          type: string
          description: transaction's notes
          example: sushi    

# to do : créer les définitions des 3 appels API